### ISSUE TITLE
Addon outdated due to XIVLauncher revamped update

### ISSUE THREAD

**Issue by eggtee** [Bluefissure/Inviter#4]
sorry in advance if I am not suppose to ask about addon update for outdated addons here.
XIVLauncher recently did a massive update and most if not all addons are outdated and requires an update.

thanks.

**Comment by Bluefissure** [comment]
This is already upgraded, you can check [this branch](https://github.com/Bluefissure/DalamudPlugins/tree/Bluefissure-api4) for installation. What you need to do is to replace the third-party repo link to my api4 branch.

I was thinking of replacing my old branch but since some users in CN are still using Dalamud api3 (cuz the update is not mandatory in CN), I don't want to force them to use the new one.
