### ISSUE TITLE
Performance drop when using look-ahead/behinds in combat

### ISSUE THREAD

**Issue by Jaksuhn** [Bluefissure/Inviter#7]
This is incredibly specific and ultimately not a big deal, but I suppose warrants a report.

Under the conditions of:
- Having a match pattern with look-ahead/behinds
- Being in combat with many people around (world fates, bozja, hunt marks, etc)

Frame rate drops from my typical 144 to sub 20 for as long as the pattern is enabled, even if the party is full and it isn't actually doing anything. This does not happen with just look-ahead/behinds, nor does just being in combat trigger it, nor many people around. It is specifically all three of those together does performance tank.

This was the exact pattern: (?!.+(z2|z1))(inv|Inv|lfg|LFG|lfp|LFP)(?<!(z2|z1).+)

**Comment by Bluefissure** [comment]
I should not compile the regex since it won't be re-used in https://github.com/Bluefissure/Inviter/blob/main/Inviter/Inviter.cs#L332.
I think Aireil told me that but I didn't make an update.
BTW I think the battle logs are in the Notice channel and I forgot to add it to the hidden chat types.
I can make a fix later today and before that you can add the Notice channel to the filtered channels or just disable it while in combat.

**Comment by Jaksuhn** [comment]
The only channels I have enabled are say, shout, and yell. Already had notice disabled. And yeah, I do usually just disable it when this happens. Enable/disable is on a hotbar so like I said, not a big deal.

**Comment by Bluefissure** [comment]
Should be good in v1.0.7.0
